/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 25-Jun-2019 22:48:15
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 9
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */

/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2018b\extern\include\tmwtypes.h 
 */
const int BL = 9;
const real64_T B[9] = {
    0.00206414732067,  0.02625576541967,   0.1192404023228,    0.254648892005,
     0.3214693957925,    0.254648892005,   0.1192404023228,  0.02625576541967,
    0.00206414732067
};
